# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmitry/CLionProjects/BattleOfRaces

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmitry/CLionProjects/BattleOfRaces

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitry/CLionProjects/BattleOfRaces/CMakeFiles /home/dmitry/CLionProjects/BattleOfRaces/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitry/CLionProjects/BattleOfRaces/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BattleOfRaces

# Build rule for target.
BattleOfRaces: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BattleOfRaces
.PHONY : BattleOfRaces

# fast build rule for target.
BattleOfRaces/fast:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/build
.PHONY : BattleOfRaces/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/main.cpp.s
.PHONY : main.cpp.s

sources/CArcher.o: sources/CArcher.cpp.o

.PHONY : sources/CArcher.o

# target to build an object file
sources/CArcher.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CArcher.cpp.o
.PHONY : sources/CArcher.cpp.o

sources/CArcher.i: sources/CArcher.cpp.i

.PHONY : sources/CArcher.i

# target to preprocess a source file
sources/CArcher.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CArcher.cpp.i
.PHONY : sources/CArcher.cpp.i

sources/CArcher.s: sources/CArcher.cpp.s

.PHONY : sources/CArcher.s

# target to generate assembly for a file
sources/CArcher.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CArcher.cpp.s
.PHONY : sources/CArcher.cpp.s

sources/CBarack.o: sources/CBarack.cpp.o

.PHONY : sources/CBarack.o

# target to build an object file
sources/CBarack.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CBarack.cpp.o
.PHONY : sources/CBarack.cpp.o

sources/CBarack.i: sources/CBarack.cpp.i

.PHONY : sources/CBarack.i

# target to preprocess a source file
sources/CBarack.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CBarack.cpp.i
.PHONY : sources/CBarack.cpp.i

sources/CBarack.s: sources/CBarack.cpp.s

.PHONY : sources/CBarack.s

# target to generate assembly for a file
sources/CBarack.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CBarack.cpp.s
.PHONY : sources/CBarack.cpp.s

sources/CBuilding.o: sources/CBuilding.cpp.o

.PHONY : sources/CBuilding.o

# target to build an object file
sources/CBuilding.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CBuilding.cpp.o
.PHONY : sources/CBuilding.cpp.o

sources/CBuilding.i: sources/CBuilding.cpp.i

.PHONY : sources/CBuilding.i

# target to preprocess a source file
sources/CBuilding.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CBuilding.cpp.i
.PHONY : sources/CBuilding.cpp.i

sources/CBuilding.s: sources/CBuilding.cpp.s

.PHONY : sources/CBuilding.s

# target to generate assembly for a file
sources/CBuilding.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CBuilding.cpp.s
.PHONY : sources/CBuilding.cpp.s

sources/CCannonTower.o: sources/CCannonTower.cpp.o

.PHONY : sources/CCannonTower.o

# target to build an object file
sources/CCannonTower.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CCannonTower.cpp.o
.PHONY : sources/CCannonTower.cpp.o

sources/CCannonTower.i: sources/CCannonTower.cpp.i

.PHONY : sources/CCannonTower.i

# target to preprocess a source file
sources/CCannonTower.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CCannonTower.cpp.i
.PHONY : sources/CCannonTower.cpp.i

sources/CCannonTower.s: sources/CCannonTower.cpp.s

.PHONY : sources/CCannonTower.s

# target to generate assembly for a file
sources/CCannonTower.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CCannonTower.cpp.s
.PHONY : sources/CCannonTower.cpp.s

sources/CCatapult.o: sources/CCatapult.cpp.o

.PHONY : sources/CCatapult.o

# target to build an object file
sources/CCatapult.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CCatapult.cpp.o
.PHONY : sources/CCatapult.cpp.o

sources/CCatapult.i: sources/CCatapult.cpp.i

.PHONY : sources/CCatapult.i

# target to preprocess a source file
sources/CCatapult.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CCatapult.cpp.i
.PHONY : sources/CCatapult.cpp.i

sources/CCatapult.s: sources/CCatapult.cpp.s

.PHONY : sources/CCatapult.s

# target to generate assembly for a file
sources/CCatapult.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CCatapult.cpp.s
.PHONY : sources/CCatapult.cpp.s

sources/CFactoryArcher.o: sources/CFactoryArcher.cpp.o

.PHONY : sources/CFactoryArcher.o

# target to build an object file
sources/CFactoryArcher.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryArcher.cpp.o
.PHONY : sources/CFactoryArcher.cpp.o

sources/CFactoryArcher.i: sources/CFactoryArcher.cpp.i

.PHONY : sources/CFactoryArcher.i

# target to preprocess a source file
sources/CFactoryArcher.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryArcher.cpp.i
.PHONY : sources/CFactoryArcher.cpp.i

sources/CFactoryArcher.s: sources/CFactoryArcher.cpp.s

.PHONY : sources/CFactoryArcher.s

# target to generate assembly for a file
sources/CFactoryArcher.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryArcher.cpp.s
.PHONY : sources/CFactoryArcher.cpp.s

sources/CFactoryBarack.o: sources/CFactoryBarack.cpp.o

.PHONY : sources/CFactoryBarack.o

# target to build an object file
sources/CFactoryBarack.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryBarack.cpp.o
.PHONY : sources/CFactoryBarack.cpp.o

sources/CFactoryBarack.i: sources/CFactoryBarack.cpp.i

.PHONY : sources/CFactoryBarack.i

# target to preprocess a source file
sources/CFactoryBarack.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryBarack.cpp.i
.PHONY : sources/CFactoryBarack.cpp.i

sources/CFactoryBarack.s: sources/CFactoryBarack.cpp.s

.PHONY : sources/CFactoryBarack.s

# target to generate assembly for a file
sources/CFactoryBarack.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryBarack.cpp.s
.PHONY : sources/CFactoryBarack.cpp.s

sources/CFactoryCannonTower.o: sources/CFactoryCannonTower.cpp.o

.PHONY : sources/CFactoryCannonTower.o

# target to build an object file
sources/CFactoryCannonTower.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryCannonTower.cpp.o
.PHONY : sources/CFactoryCannonTower.cpp.o

sources/CFactoryCannonTower.i: sources/CFactoryCannonTower.cpp.i

.PHONY : sources/CFactoryCannonTower.i

# target to preprocess a source file
sources/CFactoryCannonTower.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryCannonTower.cpp.i
.PHONY : sources/CFactoryCannonTower.cpp.i

sources/CFactoryCannonTower.s: sources/CFactoryCannonTower.cpp.s

.PHONY : sources/CFactoryCannonTower.s

# target to generate assembly for a file
sources/CFactoryCannonTower.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryCannonTower.cpp.s
.PHONY : sources/CFactoryCannonTower.cpp.s

sources/CFactoryCatapult.o: sources/CFactoryCatapult.cpp.o

.PHONY : sources/CFactoryCatapult.o

# target to build an object file
sources/CFactoryCatapult.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryCatapult.cpp.o
.PHONY : sources/CFactoryCatapult.cpp.o

sources/CFactoryCatapult.i: sources/CFactoryCatapult.cpp.i

.PHONY : sources/CFactoryCatapult.i

# target to preprocess a source file
sources/CFactoryCatapult.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryCatapult.cpp.i
.PHONY : sources/CFactoryCatapult.cpp.i

sources/CFactoryCatapult.s: sources/CFactoryCatapult.cpp.s

.PHONY : sources/CFactoryCatapult.s

# target to generate assembly for a file
sources/CFactoryCatapult.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryCatapult.cpp.s
.PHONY : sources/CFactoryCatapult.cpp.s

sources/CFactoryFarm.o: sources/CFactoryFarm.cpp.o

.PHONY : sources/CFactoryFarm.o

# target to build an object file
sources/CFactoryFarm.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryFarm.cpp.o
.PHONY : sources/CFactoryFarm.cpp.o

sources/CFactoryFarm.i: sources/CFactoryFarm.cpp.i

.PHONY : sources/CFactoryFarm.i

# target to preprocess a source file
sources/CFactoryFarm.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryFarm.cpp.i
.PHONY : sources/CFactoryFarm.cpp.i

sources/CFactoryFarm.s: sources/CFactoryFarm.cpp.s

.PHONY : sources/CFactoryFarm.s

# target to generate assembly for a file
sources/CFactoryFarm.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryFarm.cpp.s
.PHONY : sources/CFactoryFarm.cpp.s

sources/CFactoryHorseman.o: sources/CFactoryHorseman.cpp.o

.PHONY : sources/CFactoryHorseman.o

# target to build an object file
sources/CFactoryHorseman.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryHorseman.cpp.o
.PHONY : sources/CFactoryHorseman.cpp.o

sources/CFactoryHorseman.i: sources/CFactoryHorseman.cpp.i

.PHONY : sources/CFactoryHorseman.i

# target to preprocess a source file
sources/CFactoryHorseman.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryHorseman.cpp.i
.PHONY : sources/CFactoryHorseman.cpp.i

sources/CFactoryHorseman.s: sources/CFactoryHorseman.cpp.s

.PHONY : sources/CFactoryHorseman.s

# target to generate assembly for a file
sources/CFactoryHorseman.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryHorseman.cpp.s
.PHONY : sources/CFactoryHorseman.cpp.s

sources/CFactoryInfant.o: sources/CFactoryInfant.cpp.o

.PHONY : sources/CFactoryInfant.o

# target to build an object file
sources/CFactoryInfant.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryInfant.cpp.o
.PHONY : sources/CFactoryInfant.cpp.o

sources/CFactoryInfant.i: sources/CFactoryInfant.cpp.i

.PHONY : sources/CFactoryInfant.i

# target to preprocess a source file
sources/CFactoryInfant.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryInfant.cpp.i
.PHONY : sources/CFactoryInfant.cpp.i

sources/CFactoryInfant.s: sources/CFactoryInfant.cpp.s

.PHONY : sources/CFactoryInfant.s

# target to generate assembly for a file
sources/CFactoryInfant.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryInfant.cpp.s
.PHONY : sources/CFactoryInfant.cpp.s

sources/CFactoryPeasant.o: sources/CFactoryPeasant.cpp.o

.PHONY : sources/CFactoryPeasant.o

# target to build an object file
sources/CFactoryPeasant.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryPeasant.cpp.o
.PHONY : sources/CFactoryPeasant.cpp.o

sources/CFactoryPeasant.i: sources/CFactoryPeasant.cpp.i

.PHONY : sources/CFactoryPeasant.i

# target to preprocess a source file
sources/CFactoryPeasant.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryPeasant.cpp.i
.PHONY : sources/CFactoryPeasant.cpp.i

sources/CFactoryPeasant.s: sources/CFactoryPeasant.cpp.s

.PHONY : sources/CFactoryPeasant.s

# target to generate assembly for a file
sources/CFactoryPeasant.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryPeasant.cpp.s
.PHONY : sources/CFactoryPeasant.cpp.s

sources/CFactoryTowerOfWizard.o: sources/CFactoryTowerOfWizard.cpp.o

.PHONY : sources/CFactoryTowerOfWizard.o

# target to build an object file
sources/CFactoryTowerOfWizard.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryTowerOfWizard.cpp.o
.PHONY : sources/CFactoryTowerOfWizard.cpp.o

sources/CFactoryTowerOfWizard.i: sources/CFactoryTowerOfWizard.cpp.i

.PHONY : sources/CFactoryTowerOfWizard.i

# target to preprocess a source file
sources/CFactoryTowerOfWizard.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryTowerOfWizard.cpp.i
.PHONY : sources/CFactoryTowerOfWizard.cpp.i

sources/CFactoryTowerOfWizard.s: sources/CFactoryTowerOfWizard.cpp.s

.PHONY : sources/CFactoryTowerOfWizard.s

# target to generate assembly for a file
sources/CFactoryTowerOfWizard.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryTowerOfWizard.cpp.s
.PHONY : sources/CFactoryTowerOfWizard.cpp.s

sources/CFactoryTownHall.o: sources/CFactoryTownHall.cpp.o

.PHONY : sources/CFactoryTownHall.o

# target to build an object file
sources/CFactoryTownHall.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryTownHall.cpp.o
.PHONY : sources/CFactoryTownHall.cpp.o

sources/CFactoryTownHall.i: sources/CFactoryTownHall.cpp.i

.PHONY : sources/CFactoryTownHall.i

# target to preprocess a source file
sources/CFactoryTownHall.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryTownHall.cpp.i
.PHONY : sources/CFactoryTownHall.cpp.i

sources/CFactoryTownHall.s: sources/CFactoryTownHall.cpp.s

.PHONY : sources/CFactoryTownHall.s

# target to generate assembly for a file
sources/CFactoryTownHall.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryTownHall.cpp.s
.PHONY : sources/CFactoryTownHall.cpp.s

sources/CFactoryWizzard.o: sources/CFactoryWizzard.cpp.o

.PHONY : sources/CFactoryWizzard.o

# target to build an object file
sources/CFactoryWizzard.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryWizzard.cpp.o
.PHONY : sources/CFactoryWizzard.cpp.o

sources/CFactoryWizzard.i: sources/CFactoryWizzard.cpp.i

.PHONY : sources/CFactoryWizzard.i

# target to preprocess a source file
sources/CFactoryWizzard.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryWizzard.cpp.i
.PHONY : sources/CFactoryWizzard.cpp.i

sources/CFactoryWizzard.s: sources/CFactoryWizzard.cpp.s

.PHONY : sources/CFactoryWizzard.s

# target to generate assembly for a file
sources/CFactoryWizzard.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFactoryWizzard.cpp.s
.PHONY : sources/CFactoryWizzard.cpp.s

sources/CFarm.o: sources/CFarm.cpp.o

.PHONY : sources/CFarm.o

# target to build an object file
sources/CFarm.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFarm.cpp.o
.PHONY : sources/CFarm.cpp.o

sources/CFarm.i: sources/CFarm.cpp.i

.PHONY : sources/CFarm.i

# target to preprocess a source file
sources/CFarm.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFarm.cpp.i
.PHONY : sources/CFarm.cpp.i

sources/CFarm.s: sources/CFarm.cpp.s

.PHONY : sources/CFarm.s

# target to generate assembly for a file
sources/CFarm.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CFarm.cpp.s
.PHONY : sources/CFarm.cpp.s

sources/CHorseman.o: sources/CHorseman.cpp.o

.PHONY : sources/CHorseman.o

# target to build an object file
sources/CHorseman.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CHorseman.cpp.o
.PHONY : sources/CHorseman.cpp.o

sources/CHorseman.i: sources/CHorseman.cpp.i

.PHONY : sources/CHorseman.i

# target to preprocess a source file
sources/CHorseman.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CHorseman.cpp.i
.PHONY : sources/CHorseman.cpp.i

sources/CHorseman.s: sources/CHorseman.cpp.s

.PHONY : sources/CHorseman.s

# target to generate assembly for a file
sources/CHorseman.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CHorseman.cpp.s
.PHONY : sources/CHorseman.cpp.s

sources/CInfant.o: sources/CInfant.cpp.o

.PHONY : sources/CInfant.o

# target to build an object file
sources/CInfant.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CInfant.cpp.o
.PHONY : sources/CInfant.cpp.o

sources/CInfant.i: sources/CInfant.cpp.i

.PHONY : sources/CInfant.i

# target to preprocess a source file
sources/CInfant.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CInfant.cpp.i
.PHONY : sources/CInfant.cpp.i

sources/CInfant.s: sources/CInfant.cpp.s

.PHONY : sources/CInfant.s

# target to generate assembly for a file
sources/CInfant.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CInfant.cpp.s
.PHONY : sources/CInfant.cpp.s

sources/CPeasant.o: sources/CPeasant.cpp.o

.PHONY : sources/CPeasant.o

# target to build an object file
sources/CPeasant.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CPeasant.cpp.o
.PHONY : sources/CPeasant.cpp.o

sources/CPeasant.i: sources/CPeasant.cpp.i

.PHONY : sources/CPeasant.i

# target to preprocess a source file
sources/CPeasant.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CPeasant.cpp.i
.PHONY : sources/CPeasant.cpp.i

sources/CPeasant.s: sources/CPeasant.cpp.s

.PHONY : sources/CPeasant.s

# target to generate assembly for a file
sources/CPeasant.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CPeasant.cpp.s
.PHONY : sources/CPeasant.cpp.s

sources/CTowerOfWizard.o: sources/CTowerOfWizard.cpp.o

.PHONY : sources/CTowerOfWizard.o

# target to build an object file
sources/CTowerOfWizard.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CTowerOfWizard.cpp.o
.PHONY : sources/CTowerOfWizard.cpp.o

sources/CTowerOfWizard.i: sources/CTowerOfWizard.cpp.i

.PHONY : sources/CTowerOfWizard.i

# target to preprocess a source file
sources/CTowerOfWizard.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CTowerOfWizard.cpp.i
.PHONY : sources/CTowerOfWizard.cpp.i

sources/CTowerOfWizard.s: sources/CTowerOfWizard.cpp.s

.PHONY : sources/CTowerOfWizard.s

# target to generate assembly for a file
sources/CTowerOfWizard.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CTowerOfWizard.cpp.s
.PHONY : sources/CTowerOfWizard.cpp.s

sources/CTownHall.o: sources/CTownHall.cpp.o

.PHONY : sources/CTownHall.o

# target to build an object file
sources/CTownHall.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CTownHall.cpp.o
.PHONY : sources/CTownHall.cpp.o

sources/CTownHall.i: sources/CTownHall.cpp.i

.PHONY : sources/CTownHall.i

# target to preprocess a source file
sources/CTownHall.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CTownHall.cpp.i
.PHONY : sources/CTownHall.cpp.i

sources/CTownHall.s: sources/CTownHall.cpp.s

.PHONY : sources/CTownHall.s

# target to generate assembly for a file
sources/CTownHall.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CTownHall.cpp.s
.PHONY : sources/CTownHall.cpp.s

sources/CWarrior.o: sources/CWarrior.cpp.o

.PHONY : sources/CWarrior.o

# target to build an object file
sources/CWarrior.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CWarrior.cpp.o
.PHONY : sources/CWarrior.cpp.o

sources/CWarrior.i: sources/CWarrior.cpp.i

.PHONY : sources/CWarrior.i

# target to preprocess a source file
sources/CWarrior.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CWarrior.cpp.i
.PHONY : sources/CWarrior.cpp.i

sources/CWarrior.s: sources/CWarrior.cpp.s

.PHONY : sources/CWarrior.s

# target to generate assembly for a file
sources/CWarrior.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CWarrior.cpp.s
.PHONY : sources/CWarrior.cpp.s

sources/CWizzard.o: sources/CWizzard.cpp.o

.PHONY : sources/CWizzard.o

# target to build an object file
sources/CWizzard.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CWizzard.cpp.o
.PHONY : sources/CWizzard.cpp.o

sources/CWizzard.i: sources/CWizzard.cpp.i

.PHONY : sources/CWizzard.i

# target to preprocess a source file
sources/CWizzard.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CWizzard.cpp.i
.PHONY : sources/CWizzard.cpp.i

sources/CWizzard.s: sources/CWizzard.cpp.s

.PHONY : sources/CWizzard.s

# target to generate assembly for a file
sources/CWizzard.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/CWizzard.cpp.s
.PHONY : sources/CWizzard.cpp.s

sources/IUnit.o: sources/IUnit.cpp.o

.PHONY : sources/IUnit.o

# target to build an object file
sources/IUnit.cpp.o:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/IUnit.cpp.o
.PHONY : sources/IUnit.cpp.o

sources/IUnit.i: sources/IUnit.cpp.i

.PHONY : sources/IUnit.i

# target to preprocess a source file
sources/IUnit.cpp.i:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/IUnit.cpp.i
.PHONY : sources/IUnit.cpp.i

sources/IUnit.s: sources/IUnit.cpp.s

.PHONY : sources/IUnit.s

# target to generate assembly for a file
sources/IUnit.cpp.s:
	$(MAKE) -f CMakeFiles/BattleOfRaces.dir/build.make CMakeFiles/BattleOfRaces.dir/sources/IUnit.cpp.s
.PHONY : sources/IUnit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... BattleOfRaces"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sources/CArcher.o"
	@echo "... sources/CArcher.i"
	@echo "... sources/CArcher.s"
	@echo "... sources/CBarack.o"
	@echo "... sources/CBarack.i"
	@echo "... sources/CBarack.s"
	@echo "... sources/CBuilding.o"
	@echo "... sources/CBuilding.i"
	@echo "... sources/CBuilding.s"
	@echo "... sources/CCannonTower.o"
	@echo "... sources/CCannonTower.i"
	@echo "... sources/CCannonTower.s"
	@echo "... sources/CCatapult.o"
	@echo "... sources/CCatapult.i"
	@echo "... sources/CCatapult.s"
	@echo "... sources/CFactoryArcher.o"
	@echo "... sources/CFactoryArcher.i"
	@echo "... sources/CFactoryArcher.s"
	@echo "... sources/CFactoryBarack.o"
	@echo "... sources/CFactoryBarack.i"
	@echo "... sources/CFactoryBarack.s"
	@echo "... sources/CFactoryCannonTower.o"
	@echo "... sources/CFactoryCannonTower.i"
	@echo "... sources/CFactoryCannonTower.s"
	@echo "... sources/CFactoryCatapult.o"
	@echo "... sources/CFactoryCatapult.i"
	@echo "... sources/CFactoryCatapult.s"
	@echo "... sources/CFactoryFarm.o"
	@echo "... sources/CFactoryFarm.i"
	@echo "... sources/CFactoryFarm.s"
	@echo "... sources/CFactoryHorseman.o"
	@echo "... sources/CFactoryHorseman.i"
	@echo "... sources/CFactoryHorseman.s"
	@echo "... sources/CFactoryInfant.o"
	@echo "... sources/CFactoryInfant.i"
	@echo "... sources/CFactoryInfant.s"
	@echo "... sources/CFactoryPeasant.o"
	@echo "... sources/CFactoryPeasant.i"
	@echo "... sources/CFactoryPeasant.s"
	@echo "... sources/CFactoryTowerOfWizard.o"
	@echo "... sources/CFactoryTowerOfWizard.i"
	@echo "... sources/CFactoryTowerOfWizard.s"
	@echo "... sources/CFactoryTownHall.o"
	@echo "... sources/CFactoryTownHall.i"
	@echo "... sources/CFactoryTownHall.s"
	@echo "... sources/CFactoryWizzard.o"
	@echo "... sources/CFactoryWizzard.i"
	@echo "... sources/CFactoryWizzard.s"
	@echo "... sources/CFarm.o"
	@echo "... sources/CFarm.i"
	@echo "... sources/CFarm.s"
	@echo "... sources/CHorseman.o"
	@echo "... sources/CHorseman.i"
	@echo "... sources/CHorseman.s"
	@echo "... sources/CInfant.o"
	@echo "... sources/CInfant.i"
	@echo "... sources/CInfant.s"
	@echo "... sources/CPeasant.o"
	@echo "... sources/CPeasant.i"
	@echo "... sources/CPeasant.s"
	@echo "... sources/CTowerOfWizard.o"
	@echo "... sources/CTowerOfWizard.i"
	@echo "... sources/CTowerOfWizard.s"
	@echo "... sources/CTownHall.o"
	@echo "... sources/CTownHall.i"
	@echo "... sources/CTownHall.s"
	@echo "... sources/CWarrior.o"
	@echo "... sources/CWarrior.i"
	@echo "... sources/CWarrior.s"
	@echo "... sources/CWizzard.o"
	@echo "... sources/CWizzard.i"
	@echo "... sources/CWizzard.s"
	@echo "... sources/IUnit.o"
	@echo "... sources/IUnit.i"
	@echo "... sources/IUnit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

